Bump ZooKeeper to 3.8.1
Signed-off-by: Yanjun Zhou <zhouya@vmware.com>

diff --git a/build/yamls/flow-visibility.yml b/build/yamls/flow-visibility.yml
--- a/build/yamls/flow-visibility.yml
+++ b/build/yamls/flow-visibility.yml
@@ -6564,7 +6564,7 @@ metadata:
   name: zookeeper
   namespace: flow-visibility
 spec:
-  podManagementPolicy: Parallel
+  podManagementPolicy: OrderedReady
   replicas: 1
   selector:
     matchLabels:
@@ -6610,6 +6610,7 @@ spec:
             echo 'initLimit=300'
             echo 'syncLimit=10'
             echo 'maxClientCnxns=2000'
+            echo 'maxTimeToWaitForEpoch=2000'
             echo 'maxSessionTimeout=60000000'
             echo "dataDir=${ZOO_DATA_DIR}"
             echo "dataLogDir=${ZOO_DATA_LOG_DIR}"
@@ -6622,6 +6623,7 @@ spec:
             echo '4lw.commands.whitelist=*'
             echo 'metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider'
             echo "metricsProvider.httpPort=${PROMETHEUS_PORT}"
+            echo "zookeeper.skipACL=true"
           } > /conf/zoo.cfg &&
           {
             echo "zookeeper.root.logger=CONSOLE"
@@ -6630,15 +6632,15 @@ spec:
             echo "log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender"
             echo "log4j.appender.CONSOLE.Threshold=\${zookeeper.console.threshold}"
             echo "log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout"
-            echo "log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n"
+            echo "log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} - %-5p [%t:%C{1}@%L] - %m%n"
           } > /conf/log4j.properties &&
-          echo 'JVMFLAGS="-Xms128M -Xmx4G -XX:+UseG1GC -XX:+CMSParallelRemarkEnabled -XX:ActiveProcessorCount=8"' > /conf/java.env &&
+          echo 'JVMFLAGS="-Xms128M -Xmx4G -XX:ActiveProcessorCount=8 -XX:+AlwaysPreTouch -Djute.maxbuffer=8388608 -XX:MaxGCPauseMillis=50"' > /conf/java.env &&
           if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
-              NAME=${BASH_REMATCH[1]}
-              ORD=${BASH_REMATCH[2]}
+              NAME=${BASH_REMATCH[1]} &&
+              ORD=${BASH_REMATCH[2]};
           else
-              echo "Failed to parse name and ordinal of Pod"
-              exit 1
+              echo "Failed to parse name and ordinal of Pod" &&
+              exit 1;
           fi &&
           mkdir -p ${ZOO_DATA_DIR} &&
           mkdir -p ${ZOO_DATA_LOG_DIR} &&
@@ -6663,19 +6665,20 @@ spec:
               fi
               echo "weight.$i=$WEIGHT" >> /conf/zoo.cfg;
           done &&
-          chown -Rv zookeeper "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR" "$ZOO_LOG_DIR" "$ZOO_CONF_DIR" &&
           zkServer.sh start-foreground
-        image: projects.registry.vmware.com/antrea/theia-zookeeper:3.8.0
+        image: docker.io/zookeeper:3.8.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
           exec:
             command:
             - bash
-            - -c
-            - OK=$(echo ruok | nc 127.0.0.1 2181); if [[ "$OK" == "imok" ]]; then
-              exit 0; else exit 1; fi
-          initialDelaySeconds: 10
-          timeoutSeconds: 5
+            - -xc
+            - date && OK=$(exec 3<>/dev/tcp/127.0.0.1/2181 ; printf "ruok" >&3 ; IFS=;
+              tee <&3; exec 3<&- ;); if [[ "$OK" == "imok" ]]; then exit 0; else exit
+              1; fi
+            exec: null
+          initialDelaySeconds: 20
+          timeoutSeconds: 15
         name: kubernetes-zookeeper
         ports:
         - containerPort: 2181
@@ -6691,18 +6694,18 @@ spec:
             command:
             - bash
             - -c
-            - OK=$(echo ruok | nc 127.0.0.1 2181); if [[ "$OK" == "imok" ]]; then
-              STATE=$(echo mntr | nc 127.0.0.1 2181 | grep zk_server_state | cut -d
-              " " -f 2); if [[ "$STATE" == "leader" ]]; then SYNCED_FOLLOWERS=$(echo
-              mntr | nc 127.0.0.1 2181 | grep zk_synced_followers | cut -d " " -f
-              2 | cut -d "." -f 1); if [[ $SYNCED_FOLLOWERS == $(( $SERVERS - 1 ))
-              ]]; then ./bin/zkCli.sh ls /; exit $?; else exit 1; fi; elif [[ "$STATE"
-              == "follower" ]]; then PEER_STATE=$(echo mntr | nc 127.0.0.1 2181 |
-              grep zk_peer_state); if [[ "$PEER_STATE" == "following - broadcast"
-              ]]; then ./bin/zkCli.sh ls /; exit $?; else exit 1; fi; fi; else exit
-              1; fi
-          initialDelaySeconds: 10
-          timeoutSeconds: 5
+            - OK=$(exec 3<>/dev/tcp/127.0.0.1/2181 ; printf "ruok" >&3 ; IFS=; tee
+              <&3; exec 3<&- ;); if [[ "$OK" == "imok" ]]; then STATE=$(echo mntr
+              | nc 127.0.0.1 2181 | grep zk_server_state | cut -d " " -f 2); if [[
+              "$STATE" == "leader" ]]; then SYNCED_FOLLOWERS=$(echo mntr | nc 127.0.0.1
+              2181 | grep zk_synced_followers | cut -d " " -f 2 | cut -d "." -f 1);
+              if [[ $SYNCED_FOLLOWERS == $(( $SERVERS - 1 )) ]]; then ./bin/zkCli.sh
+              ls /; exit $?; else exit 1; fi; elif [[ "$STATE" == "follower" ]]; then
+              PEER_STATE=$(echo mntr | nc 127.0.0.1 2181 | grep zk_peer_state); if
+              [[ "$PEER_STATE" == "following - broadcast" ]]; then ./bin/zkCli.sh
+              ls /; exit $?; else exit 1; fi; fi; else exit 1; fi
+          initialDelaySeconds: 20
+          timeoutSeconds: 15
         resources:
           limits:
             cpu: "2"
